/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FdButton: typeof import('./../components/fd-button/index.vue')['default']
    FdDialogForm: typeof import('./../components/fd-dialog-form/index.vue')['default']
    FdForm: typeof import('./../components/fd-form/index.vue')['default']
    FdFormNumber: typeof import('./../components/fd-form-number/index.vue')['default']
    FdFormSelect: typeof import('./../components/fd-form-select/index.vue')['default']
    FdFormText: typeof import('./../components/fd-form-text/index.vue')['default']
    FdNumber: typeof import('./../components/fd-number/index.vue')['default']
    FdSelect: typeof import('./../components/fd-select/index.vue')['default']
    FdTable: typeof import('./../components/fd-table/index.vue')['default']
    FdText: typeof import('./../components/fd-text/index.vue')['default']
    TableColumns: typeof import('./../components/fd-table/tableColumns.vue')['default']
  }
}
